import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  root: {
    background: "linear-gradient(180deg, #e8f5e9 0%, #f5f5f5 100%)",
    minHeight: "100vh",
    paddingTop: 20,
    paddingBottom: 40,
  },
  pageHeader: {
    textAlign: "center",
    marginTop: 20,
    marginBottom: 24,
    padding: "0 16px",
  },
  pageTitle: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.8rem",
    color: "#1b5e20",
    marginBottom: 8,
  },
  pageSubtitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.95rem",
    color: "#666",
  },
  ayatCard: {
    background: "#fff",
    borderRadius: 24,
    padding: "24px 20px",
    margin: "0 16px",
    boxShadow: "0 8px 32px rgba(27, 94, 32, 0.12)",
    position: "relative",
    overflow: "hidden",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 4,
      background: "linear-gradient(90deg, #1b5e20 0%, #4caf50 50%, #81c784 100%)",
    },
  },
  surahBadge: {
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 16,
    padding: "16px 20px",
    marginBottom: 24,
    textAlign: "center",
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(27, 94, 32, 0.3)",
    },
  },
  surahName: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "1.2rem",
    color: "#fff",
  },
  surahArabic: {
    fontFamily: "'Amiri', serif",
    fontSize: "1.5rem",
    color: "rgba(255, 255, 255, 0.9)",
    marginTop: 4,
  },
  ayatNumber: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.8rem",
    color: "rgba(255, 255, 255, 0.8)",
    marginTop: 8,
    background: "rgba(255, 255, 255, 0.15)",
    display: "inline-block",
    padding: "4px 12px",
    borderRadius: 12,
  },
  arabicText: {
    fontFamily: "'Amiri', 'Traditional Arabic', serif",
    fontSize: "1.8rem",
    lineHeight: 2.2,
    color: "#1b5e20",
    textAlign: "center",
    direction: "rtl",
    marginBottom: 20,
    padding: "16px 0",
    borderBottom: "1px solid rgba(27, 94, 32, 0.1)",
  },
  transliteration: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.9rem",
    color: "#757575",
    textAlign: "center",
    fontStyle: "italic",
    marginBottom: 16,
    lineHeight: 1.6,
  },
  translationContainer: {
    background: "linear-gradient(135deg, #f1f8e9 0%, #e8f5e9 100%)",
    borderRadius: 16,
    padding: "16px 20px",
    marginBottom: 16,
  },
  translation: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "1rem",
    color: "#333",
    textAlign: "center",
    lineHeight: 1.8,
    fontStyle: "italic",
  },
  actionButtons: {
    display: "flex",
    justifyContent: "center",
    gap: 12,
    marginTop: 8,
  },
  actionBtn: {
    color: "#1b5e20",
    backgroundColor: "rgba(27, 94, 32, 0.08)",
    "&:hover": {
      backgroundColor: "rgba(27, 94, 32, 0.15)",
    },
  },
  audioContainer: {
    margin: "24px 16px",
    "& .rhap_container": {
      borderRadius: 16,
      boxShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
      background: "#fff",
      padding: "8px 12px",
    },
    "& .rhap_main-controls-button": {
      color: "#1b5e20",
    },
    "& .rhap_progress-filled": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_progress-indicator": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_button-clear": {
      color: "#1b5e20",
    },
    "& .rhap_volume-indicator": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_volume-filled": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_time": {
      fontFamily: "'El Messiri', sans-serif",
      fontSize: "0.8rem",
      color: "#1b5e20",
    },
  },
  refreshBtn: {
    display: "flex",
    margin: "16px auto",
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.9rem",
    color: "#1b5e20",
    borderColor: "#1b5e20",
    borderRadius: 20,
    padding: "10px 24px",
    textTransform: "none",
    "&:hover": {
      borderColor: "#1b5e20",
      backgroundColor: "rgba(27, 94, 32, 0.08)",
    },
  },
  goToSurahBtn: {
    display: "flex",
    margin: "12px auto 24px",
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.95rem",
    color: "#fff",
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 20,
    padding: "12px 28px",
    textTransform: "none",
    boxShadow: "0 4px 16px rgba(27, 94, 32, 0.3)",
    "&:hover": {
      background: "linear-gradient(135deg, #2e7d32 0%, #388e3c 100%)",
      boxShadow: "0 6px 20px rgba(27, 94, 32, 0.4)",
    },
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 60,
    paddingBottom: 60,
  },
  loadingCard: {
    background: "#fff",
    borderRadius: 16,
    padding: "24px 40px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    textAlign: "center",
  },
  loadingIcon: {
    width: 50,
    height: 50,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 12px",
    position: "relative",
  },
  loadingSpinner: {
    color: "#1b5e20 !important",
  },
  loadingArabic: {
    fontFamily: "'Amiri', serif",
    fontSize: "1.3rem",
    color: "#1b5e20",
    marginBottom: 6,
  },
  loadingText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#757575",
    marginBottom: 4,
  },
  loadingDots: {
    display: "flex",
    justifyContent: "center",
    gap: 4,
    marginTop: 10,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#1b5e20",
    animation: "$bounce 1.4s infinite ease-in-out both",
    "&:nth-child(1)": {
      animationDelay: "-0.32s",
    },
    "&:nth-child(2)": {
      animationDelay: "-0.16s",
    },
    "&:nth-child(3)": {
      animationDelay: "0s",
    },
  },
  "@keyframes bounce": {
    "0%, 80%, 100%": {
      transform: "scale(0)",
    },
    "40%": {
      transform: "scale(1)",
    },
  },
}));

export default useStyles;
