import { makeStyles } from "@material-ui/core/styles";
import backgroundImg from "../../images/background.jpg";

const useStyles = makeStyles((theme) => ({
    root: {
      background: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 50%, #a5d6a7 100%)",
      minHeight: "100vh",
      padding: "0 !important",
      position: "relative",
      overflow: "hidden",
      "&::before": {
        content: '""',
        position: "absolute",
        top: -100,
        right: -100,
        width: 300,
        height: 300,
        borderRadius: "50%",
        background: "rgba(1, 121, 1, 0.1)",
      },
      "&::after": {
        content: '""',
        position: "absolute",
        bottom: -50,
        left: -50,
        width: 200,
        height: 200,
        borderRadius: "50%",
        background: "rgba(1, 121, 1, 0.08)",
      },
    },
    title: {
      color: "#1b5e20",
      fontFamily: "'Reem Kufi', 'Amiri', serif",
      fontWeight: 700,
      marginTop: 40,
      marginBottom: 12,
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.1)",
      letterSpacing: "3px",
      fontSize: "2.8rem",
      background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
    },
    captionTitle: {
      color: "#4caf50",
      textAlign: "center",
      fontFamily: "'El Messiri', 'Amiri', serif",
      fontWeight: 500,
      fontSize: "1.1rem",
      letterSpacing: "0.5px",
      opacity: 0.9,
    },
    titleContainer: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      padding: "20px 40px",
      position: "relative",
      zIndex: 1,
    },
    illustrationContainer: {
      background: "linear-gradient(180deg, #1565c0 0%, #0d47a1 100%)",
      height: 420,
      margin: "30px 20px 20px",
      borderRadius: 40,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column",
      backgroundImage: `url(${backgroundImg})`,
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundPositionX: -50,
      boxShadow: "0 20px 60px rgba(1, 121, 1, 0.3), 0 8px 25px rgba(0, 0, 0, 0.15)",
      position: "relative",
      overflow: "hidden",
      transition: "transform 0.3s ease, box-shadow 0.3s ease",
      "&:hover": {
        transform: "translateY(-5px)",
        boxShadow: "0 25px 70px rgba(1, 121, 1, 0.35), 0 12px 30px rgba(0, 0, 0, 0.2)",
      },
      "&::before": {
        content: '""',
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "linear-gradient(180deg, transparent 0%, rgba(0, 0, 0, 0.2) 100%)",
        borderRadius: 40,
      },
    },
    quranImage: {
      height: 200,
      filter: "drop-shadow(0 10px 30px rgba(0, 0, 0, 0.3))",
      transition: "transform 0.3s ease",
      position: "relative",
      zIndex: 1,
      "&:hover": {
        transform: "scale(1.05)",
      },
    },
    btnGetStarted: {
      color: "#fff",
      fontFamily: "'El Messiri', 'Reem Kufi', sans-serif",
      fontWeight: 600,
      fontSize: "1.1rem",
      padding: "14px 40px",
      borderRadius: 30,
      background: "linear-gradient(135deg, #ff9800 0%, #f57c00 100%)",
      boxShadow: "0 8px 25px rgba(255, 152, 0, 0.4)",
      textTransform: "none",
      letterSpacing: "1px",
      position: "relative",
      zIndex: 1,
      transition: "all 0.3s ease",
      marginTop: 20,
      "&:hover": {
        background: "linear-gradient(135deg, #ffa726 0%, #ff9800 100%)",
        boxShadow: "0 12px 35px rgba(255, 152, 0, 0.5)",
        transform: "translateY(-3px)",
      },
      "&:active": {
        transform: "translateY(-1px)",
        boxShadow: "0 6px 20px rgba(255, 152, 0, 0.4)",
      },
    },
    btnGetStartedContainer: {
      textAlign: 'center'
    },
    decorativeIcon: {
      position: "absolute",
      opacity: 0.1,
      color: "#1b5e20",
    },
  }));

  export default useStyles;