import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  root: {
    paddingTop: 20,
    background: "linear-gradient(180deg, #e8f5e9 0%, #f5f5f5 100%)",
    minHeight: "100vh",
    paddingBottom: 40,
  },
  heroSection: {
    textAlign: "center",
    padding: "40px 20px",
    marginTop: 20,
  },
  quranImage: {
    height: 120,
    margin: "auto",
    display: "block",
    filter: "drop-shadow(0 10px 30px rgba(27, 94, 32, 0.3))",
    marginBottom: 24,
  },
  appName: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "2rem",
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    marginBottom: 8,
  },
  appTagline: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "1rem",
    color: "#4caf50",
    marginBottom: 8,
  },
  arabicText: {
    fontFamily: "'Amiri', serif",
    fontSize: "1.4rem",
    color: "#1b5e20",
    marginTop: 16,
    opacity: 0.8,
  },
  infoCard: {
    background: "#fff",
    borderRadius: 20,
    padding: "24px",
    margin: "30px 16px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
  },
  infoTitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "1.1rem",
    color: "#1b5e20",
    marginBottom: 16,
    display: "flex",
    alignItems: "center",
    "& svg": {
      marginRight: 8,
      fontSize: 20,
    },
  },
  infoItem: {
    display: "flex",
    alignItems: "flex-start",
    marginBottom: 16,
    padding: "12px 16px",
    background: "rgba(27, 94, 32, 0.04)",
    borderRadius: 12,
    "&:last-child": {
      marginBottom: 0,
    },
  },
  infoLabel: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.85rem",
    color: "#757575",
    minWidth: 90,
  },
  infoValue: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.95rem",
    color: "#333",
    flex: 1,
  },
  link: {
    color: "#1b5e20",
    fontWeight: 600,
    textDecoration: "none",
    transition: "all 0.2s ease",
    "&:hover": {
      color: "#2e7d32",
      textDecoration: "underline",
    },
  },
  creatorSection: {
    textAlign: "center",
    marginTop: 30,
    padding: "20px",
  },
  creatorAvatar: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #1b5e20 0%, #4caf50 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 16px",
    boxShadow: "0 8px 25px rgba(27, 94, 32, 0.3)",
  },
  creatorInitial: {
    fontFamily: "'Reem Kufi', sans-serif",
    fontSize: "2rem",
    color: "#fff",
    fontWeight: 700,
  },
  creatorName: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.2rem",
    color: "#1b5e20",
    marginBottom: 4,
  },
  creatorRole: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.9rem",
    color: "#757575",
  },
  footer: {
    textAlign: "center",
    marginTop: 30,
    padding: "20px",
    borderTop: "1px solid rgba(0, 0, 0, 0.08)",
  },
  footerText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#9e9e9e",
  },
  versionBadge: {
    display: "inline-block",
    background: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    padding: "6px 16px",
    borderRadius: 20,
    marginTop: 16,
  },
  versionText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.8rem",
    color: "#1b5e20",
    fontWeight: 600,
  },
}));

export default useStyles;
