import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  root: {
    background: "linear-gradient(180deg, #e8f5e9 0%, #f5f5f5 100%)",
    minHeight: "100vh",
    paddingTop: 20,
    paddingBottom: 40,
  },
  pageHeader: {
    textAlign: "center",
    marginTop: 20,
    marginBottom: 24,
    padding: "0 16px",
  },
  pageTitle: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.8rem",
    color: "#1b5e20",
    marginBottom: 8,
  },
  pageSubtitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.95rem",
    color: "#666",
  },
  ayatCard: {
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: 24,
    padding: "40px 24px",
    margin: "0 16px",
    boxShadow: "0 16px 48px rgba(0, 0, 0, 0.2)",
    position: "relative",
    overflow: "hidden",
    minHeight: 400,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "linear-gradient(180deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0.7) 100%)",
      zIndex: 0,
    },
    "& > *": {
      position: "relative",
      zIndex: 1,
    },
  },
  arabicText: {
    fontFamily: "'Amiri', 'Traditional Arabic', serif",
    fontSize: "2rem",
    lineHeight: 2,
    color: "#fff",
    textAlign: "center",
    direction: "rtl",
    marginBottom: 24,
    padding: "20px 0",
    textShadow: "0 2px 8px rgba(0,0,0,0.5)",
  },
  translationContainer: {
    marginBottom: 24,
  },
  translation: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "1.1rem",
    color: "#fff",
    textAlign: "center",
    lineHeight: 1.8,
    fontWeight: 500,
    textShadow: "0 2px 4px rgba(0,0,0,0.5)",
  },
  surahInfo: {
    textAlign: "center",
    marginTop: 16,
    paddingTop: 16,
    borderTop: "1px solid rgba(255, 255, 255, 0.2)",
  },
  surahLabel: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontSize: "0.9rem",
    color: "rgba(255, 255, 255, 0.9)",
    letterSpacing: 2,
    textTransform: "uppercase",
    fontWeight: 600,
    textShadow: "0 1px 4px rgba(0,0,0,0.5)",
  },
  watermark: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.7rem",
    color: "rgba(255, 255, 255, 0.5)",
    letterSpacing: 1,
    position: "absolute",
    bottom: 16,
    left: 24,
    right: 24,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  actionButtons: {
    display: "flex",
    justifyContent: "center",
    gap: 12,
    marginTop: 16,
    marginBottom: 8,
  },
  actionBtn: {
    color: "#1b5e20",
    backgroundColor: "#fff",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    border: "1px solid rgba(27, 94, 32, 0.2)",
    "&:hover": {
      backgroundColor: "rgba(27, 94, 32, 0.08)",
    },
  },
  audioContainer: {
    margin: "24px 16px",
    "& .rhap_container": {
      borderRadius: 16,
      boxShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
      background: "#fff",
      padding: "8px 12px",
    },
    "& .rhap_main-controls-button": {
      color: "#1b5e20",
    },
    "& .rhap_progress-filled": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_progress-indicator": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_button-clear": {
      color: "#1b5e20",
    },
    "& .rhap_volume-indicator": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_volume-filled": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_time": {
      fontFamily: "'El Messiri', sans-serif",
      fontSize: "0.8rem",
      color: "#1b5e20",
    },
  },
  backBtn: {
    display: "flex",
    margin: "16px auto",
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.9rem",
    color: "#1b5e20",
    borderColor: "#1b5e20",
    borderRadius: 20,
    padding: "10px 24px",
    textTransform: "none",
    "&:hover": {
      borderColor: "#1b5e20",
      backgroundColor: "rgba(27, 94, 32, 0.08)",
    },
  },
  goToSurahBtn: {
    display: "flex",
    margin: "12px auto 24px",
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.95rem",
    color: "#fff",
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 20,
    padding: "12px 28px",
    textTransform: "none",
    boxShadow: "0 4px 16px rgba(27, 94, 32, 0.3)",
    "&:hover": {
      background: "linear-gradient(135deg, #2e7d32 0%, #388e3c 100%)",
      boxShadow: "0 6px 20px rgba(27, 94, 32, 0.4)",
    },
  },
  backgroundSelector: {
    margin: "16px 16px",
    padding: "12px",
    backgroundColor: "#fff",
    borderRadius: 16,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
  },
  backgroundSelectorTitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  backgroundGrid: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  backgroundThumb: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundSize: "cover",
    backgroundPosition: "center",
    cursor: "pointer",
    border: "2px solid transparent",
    transition: "all 0.2s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },
  backgroundThumbActive: {
    border: "2px solid #1b5e20",
    boxShadow: "0 2px 8px rgba(27, 94, 32, 0.4)",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 60,
    paddingBottom: 60,
  },
  loadingCard: {
    background: "#fff",
    borderRadius: 16,
    padding: "24px 40px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    textAlign: "center",
  },
  loadingIcon: {
    width: 50,
    height: 50,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 12px",
    position: "relative",
  },
  loadingSpinner: {
    color: "#1b5e20 !important",
  },
  loadingArabic: {
    fontFamily: "'Amiri', serif",
    fontSize: "1.3rem",
    color: "#1b5e20",
    marginBottom: 6,
  },
  loadingText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#757575",
    marginBottom: 4,
  },
  loadingDots: {
    display: "flex",
    justifyContent: "center",
    gap: 4,
    marginTop: 10,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#1b5e20",
    animation: "$bounce 1.4s infinite ease-in-out both",
    "&:nth-child(1)": {
      animationDelay: "-0.32s",
    },
    "&:nth-child(2)": {
      animationDelay: "-0.16s",
    },
    "&:nth-child(3)": {
      animationDelay: "0s",
    },
  },
  "@keyframes bounce": {
    "0%, 80%, 100%": {
      transform: "scale(0)",
    },
    "40%": {
      transform: "scale(1)",
    },
  },
  errorContainer: {
    textAlign: "center",
    marginTop: 60,
    padding: "0 24px",
  },
  errorText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "1rem",
    color: "#666",
    marginBottom: 16,
  },
}));

export default useStyles;
