import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  root: {
    background: "linear-gradient(180deg, #e8f5e9 0%, #f5f5f5 100%)",
    minHeight: "100vh",
    paddingTop: 20,
    paddingBottom: 30,
  },
  pageTitle: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.5rem",
    color: "#1b5e20",
    marginTop: 20,
    marginBottom: 8,
    textAlign: "center",
  },
  pageSubtitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.9rem",
    color: "#757575",
    textAlign: "center",
    marginBottom: 20,
  },
  tabsContainer: {
    display: "flex",
    gap: 10,
    padding: "0 4px",
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    padding: "12px 16px",
    borderRadius: 12,
    border: "none",
    background: "#fff",
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.9rem",
    color: "#757575",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
    "&:hover": {
      background: "#f5f5f5",
    },
  },
  tabActive: {
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    color: "#fff",
    boxShadow: "0 4px 15px rgba(27, 94, 32, 0.3)",
  },
  tabCount: {
    marginLeft: 8,
    padding: "2px 8px",
    borderRadius: 10,
    fontSize: "0.75rem",
    background: "rgba(0, 0, 0, 0.08)",
  },
  tabCountActive: {
    background: "rgba(255, 255, 255, 0.25)",
  },
  bookmarkListContainer: {
    background: "#fff",
    borderRadius: 20,
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    overflow: "hidden",
    padding: "10px 0",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
  },
  emptyIcon: {
    fontSize: "4rem",
    marginBottom: 16,
    opacity: 0.3,
  },
  emptyTitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "1.1rem",
    color: "#333",
    marginBottom: 8,
  },
  emptySubtitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#757575",
  },
  // Bookmark Surat Item
  bookmarkSuratItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    borderRadius: 12,
    margin: "2px 8px",
    "&:hover": {
      backgroundColor: "rgba(27, 94, 32, 0.06)",
    },
  },
  suratInfo: {
    display: "flex",
    alignItems: "center",
  },
  numberBadge: {
    width: 45,
    height: 45,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    borderRadius: 12,
    marginRight: 16,
    position: "relative",
    "&::before": {
      content: '""',
      position: "absolute",
      inset: 2,
      background: "#fff",
      borderRadius: 10,
    },
  },
  numberText: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1rem",
    color: "#1b5e20",
    position: "relative",
    zIndex: 1,
  },
  suratDetails: {
    textAlign: "left",
  },
  suratName: {
    fontFamily: "'El Messiri', 'Reem Kufi', sans-serif",
    fontWeight: 600,
    fontSize: "1.1rem",
    color: "#212121",
  },
  suratMeta: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.75rem",
    color: "#757575",
    marginTop: 2,
  },
  suratActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  arabicName: {
    fontFamily: "'Amiri', 'Reem Kufi', serif",
    fontSize: "1.4rem",
    color: "#1b5e20",
    marginRight: 8,
  },
  deleteBtn: {
    color: "#ef5350",
    padding: 8,
    "&:hover": {
      backgroundColor: "rgba(239, 83, 80, 0.1)",
    },
  },
  // Bookmark Ayat Item
  bookmarkAyatItem: {
    padding: "16px",
    margin: "8px",
    borderRadius: 16,
    backgroundColor: "#fff",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      boxShadow: "0 4px 15px rgba(0, 0, 0, 0.1)",
    },
  },
  ayatHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  ayatBadge: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  ayatNumberBadge: {
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 8,
  },
  ayatNumberText: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "0.8rem",
    color: "#fff",
  },
  ayatSuratName: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.85rem",
    color: "#1b5e20",
  },
  arabicText: {
    textAlign: "right",
    fontFamily: "'Amiri', serif",
    fontSize: "1.4rem",
    lineHeight: 2,
    color: "#1b5e20",
    marginBottom: 8,
    direction: "rtl",
  },
  translationText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#555",
    lineHeight: 1.5,
  },
}));

export default useStyles;
