import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  root: {
    background: "linear-gradient(180deg, #e8f5e9 0%, #f5f5f5 100%)",
    minHeight: "100vh",
    paddingTop: 20,
    paddingBottom: 40,
  },
  headerCard: {
    textAlign: "center",
    padding: "24px 20px",
    marginBottom: 16,
    marginTop: 20,
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)",
    borderRadius: 20,
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 8px 32px rgba(27, 94, 32, 0.3)",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.05'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
      opacity: 0.5,
    },
  },
  pageIcon: {
    fontSize: "2.5rem",
    marginBottom: 8,
  },
  pageTitle: {
    fontFamily: "'Reem Kufi', 'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.5rem",
    color: "#fff",
    textShadow: "0 2px 4px rgba(0, 0, 0, 0.2)",
    position: "relative",
    zIndex: 1,
  },
  pageSubtitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.9rem",
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 6,
    position: "relative",
    zIndex: 1,
  },
  // Selection Card
  selectionCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: "20px",
    marginBottom: 16,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
  },
  selectionTitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "1rem",
    color: "#1b5e20",
    marginBottom: 12,
  },
  selectContainer: {
    marginBottom: 16,
    position: "relative",
  },
  selectLabel: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#666",
    marginBottom: 6,
    display: "block",
  },
  select: {
    fontFamily: "'El Messiri', sans-serif",
    borderRadius: 12,
    "& .MuiSelect-select": {
      fontFamily: "'El Messiri', sans-serif",
      padding: "12px 14px",
    },
    "& .MuiOutlinedInput-notchedOutline": {
      borderColor: "rgba(27, 94, 32, 0.3)",
      borderRadius: 12,
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      borderColor: "#1b5e20",
    },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      borderColor: "#1b5e20",
    },
  },
  // Custom Menu Dropdown
  menuPaper: {
    borderRadius: 16,
    marginTop: 8,
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.15)",
    maxHeight: 350,
    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-track": {
      background: "#f1f1f1",
      borderRadius: 3,
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#1b5e20",
      borderRadius: 3,
    },
  },
  menuList: {
    paddingRight: "0 !important",
    width: "100% !important",
    padding: "6px",
  },
  menuItem: {
    fontFamily: "'El Messiri', sans-serif",
    borderRadius: 10,
    margin: "2px 0",
    transition: "all 0.2s ease",
    whiteSpace: "normal",
    overflow: "hidden",
    "&:hover": {
      backgroundColor: "rgba(27, 94, 32, 0.08)",
    },
    "&.Mui-selected": {
      backgroundColor: "rgba(27, 94, 32, 0.15)",
      "&:hover": {
        backgroundColor: "rgba(27, 94, 32, 0.2)",
      },
    },
  },
  menuItemDisabled: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#999",
    padding: "10px",
    textAlign: "center",
    borderBottom: "1px solid rgba(0, 0, 0, 0.08)",
    marginBottom: 4,
  },
  // Surah Item in Dropdown
  surahMenuItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    gap: 10,
    overflow: "hidden",
  },
  surahNumberBadge: {
    width: 32,
    height: 32,
    minWidth: 32,
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  surahNumberText: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "0.75rem",
    color: "#fff",
  },
  surahDetails: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
  },
  surahNameRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  surahNameLatin: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.85rem",
    color: "#1b5e20",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  surahNameArabic: {
    fontFamily: "'Amiri', serif",
    fontSize: "0.9rem",
    color: "#2e7d32",
    flexShrink: 0,
  },
  surahTranslation: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.7rem",
    color: "#888",
    marginTop: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  surahMeta: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 3,
  },
  surahMetaBadge: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.6rem",
    color: "#666",
    backgroundColor: "rgba(27, 94, 32, 0.1)",
    padding: "1px 6px",
    borderRadius: 8,
    whiteSpace: "nowrap",
  },
  // Ayat MenuItem
  ayatMenuItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  ayatBadge: {
    width: 28,
    height: 28,
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ayatBadgeText: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "0.75rem",
    color: "#fff",
  },
  startButton: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    borderRadius: 12,
    padding: "12px 24px",
    textTransform: "none",
    fontSize: "1rem",
  },
  // Memorization Area
  memorizationArea: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: "20px",
    marginBottom: 16,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
  },
  surahInfo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: "1px solid rgba(0, 0, 0, 0.08)",
  },
  surahName: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    fontSize: "1rem",
    color: "#1b5e20",
  },
  ayatProgress: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.85rem",
    color: "#666",
    backgroundColor: "rgba(27, 94, 32, 0.1)",
    padding: "4px 12px",
    borderRadius: 20,
  },
  // Ayat Card
  ayatCard: {
    backgroundColor: "rgba(27, 94, 32, 0.04)",
    borderRadius: 12,
    padding: "20px",
    marginBottom: 16,
    position: "relative",
  },
  ayatNumber: {
    position: "absolute",
    top: 12,
    left: 12,
    width: 32,
    height: 32,
    background: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ayatNumberText: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "0.85rem",
    color: "#fff",
  },
  arabicText: {
    textAlign: "right",
    fontFamily: "'Amiri', serif",
    fontSize: "1.8rem",
    lineHeight: 2.2,
    color: "#1b5e20",
    marginBottom: 16,
    direction: "rtl",
    paddingTop: 40,
  },
  hiddenText: {
    filter: "blur(10px)",
    userSelect: "none",
    transition: "filter 0.3s ease",
  },
  translationText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.95rem",
    color: "#555",
    lineHeight: 1.6,
    paddingTop: 12,
    borderTop: "1px dashed rgba(0, 0, 0, 0.1)",
  },
  // Control Buttons
  controlButtons: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 16,
  },
  controlBtn: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    borderRadius: 12,
    padding: "10px 20px",
    textTransform: "none",
    fontSize: "0.9rem",
    minWidth: 140,
  },
  hideBtn: {
    backgroundColor: "#ff9800",
    color: "#fff",
    "&:hover": {
      backgroundColor: "#f57c00",
    },
  },
  showBtn: {
    backgroundColor: "#4caf50",
    color: "#fff",
    "&:hover": {
      backgroundColor: "#388e3c",
    },
  },
  // Quiz Section
  quizSection: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: "20px",
    marginBottom: 16,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
    border: "2px solid #ff9800",
  },
  quizHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  quizIcon: {
    fontSize: "1.5rem",
    color: "#ff9800",
  },
  quizTitle: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.1rem",
    color: "#ff9800",
  },
  quizQuestion: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.95rem",
    color: "#555",
    marginBottom: 16,
    padding: "12px",
    backgroundColor: "rgba(255, 152, 0, 0.1)",
    borderRadius: 8,
  },
  quizAyatPreview: {
    textAlign: "right",
    fontFamily: "'Amiri', serif",
    fontSize: "1.5rem",
    lineHeight: 2,
    color: "#1b5e20",
    marginBottom: 16,
    direction: "rtl",
    padding: "16px",
    backgroundColor: "rgba(27, 94, 32, 0.05)",
    borderRadius: 8,
    borderRight: "4px solid #1b5e20",
  },
  quizAnswer: {
    textAlign: "right",
    fontFamily: "'Amiri', serif",
    fontSize: "1.5rem",
    lineHeight: 2,
    color: "#2e7d32",
    direction: "rtl",
    padding: "16px",
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 8,
    borderRight: "4px solid #4caf50",
    marginBottom: 16,
  },
  quizButtons: {
    display: "flex",
    gap: 12,
    justifyContent: "center",
  },
  revealBtn: {
    backgroundColor: "#1b5e20",
    color: "#fff",
    "&:hover": {
      backgroundColor: "#145214",
    },
  },
  nextQuizBtn: {
    backgroundColor: "#ff9800",
    color: "#fff",
    "&:hover": {
      backgroundColor: "#f57c00",
    },
  },
  // Navigation
  navigationButtons: {
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    marginTop: 16,
  },
  navBtn: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    borderRadius: 12,
    padding: "10px 16px",
    textTransform: "none",
    fontSize: "0.85rem",
    flex: 1,
  },
  // Audio Player
  audioContainer: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: "16px",
    marginBottom: 16,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
    "& .rhap_container": {
      borderRadius: 12,
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
      background: "#f8faf8",
      padding: "8px 12px",
    },
    "& .rhap_main-controls-button": {
      color: "#1b5e20",
    },
    "& .rhap_progress-filled": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_progress-indicator": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_button-clear": {
      color: "#1b5e20",
    },
    "& .rhap_volume-indicator": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_volume-filled": {
      backgroundColor: "#1b5e20",
    },
    "& .rhap_time": {
      fontFamily: "'El Messiri', sans-serif",
      fontSize: "0.8rem",
      color: "#1b5e20",
    },
  },
  // Loading
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    paddingBottom: 60,
  },
  loadingCard: {
    background: "#fff",
    borderRadius: 16,
    padding: "24px 40px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    textAlign: "center",
  },
  loadingSpinner: {
    color: "#1b5e20 !important",
    marginBottom: 12,
  },
  loadingText: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.9rem",
    color: "#757575",
  },
  // Mode Tabs
  modeTabs: {
    display: "flex",
    gap: 8,
    marginBottom: 16,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 8,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
  },
  modeTab: {
    flex: 1,
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    borderRadius: 8,
    padding: "12px 16px",
    textTransform: "none",
    fontSize: "0.9rem",
    color: "#666",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "rgba(27, 94, 32, 0.08)",
    },
  },
  modeTabActive: {
    backgroundColor: "#1b5e20",
    color: "#fff",
    "&:hover": {
      backgroundColor: "#145214",
    },
  },
  // Stats Card
  statsCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: "16px 20px",
    marginBottom: 16,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
    display: "flex",
    justifyContent: "space-around",
    textAlign: "center",
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  statValue: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 700,
    fontSize: "1.5rem",
    color: "#1b5e20",
  },
  statLabel: {
    fontFamily: "'El Messiri', sans-serif",
    fontSize: "0.75rem",
    color: "#888",
  },
  // Change Surah Button
  changeSurahBtn: {
    fontFamily: "'El Messiri', sans-serif",
    fontWeight: 600,
    textTransform: "none",
    fontSize: "0.9rem",
    marginTop: 16,
  },
}));

export default useStyles;
